### ISSUE TITLE
启动时异常退出

### ISSUE THREAD

**Issue by g-bo-wen** [ClaymanTwinkle/FlySword#1]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fly Sword Mod (flysword)

Caused by: java.lang.NoSuchMethodError: com.flysword.enchantment.EnchantmentFlySword.setName(Ljava/lang/String;)Lnet/minecraft/enchantment/Enchantment;

	at com.flysword.enchantment.EnchantmentFlySword.<init>(EnchantmentFlySword.java:15)

	at com.flysword.enchantment.MyEnchantments.init(MyEnchantments.java:12)

	at com.flysword.CommonProxy.preInit(CommonProxy.java:19)

	at com.flysword.client.ClientProxy.preInit(ClientProxy.java:14)

	at com.flysword.FlySwordMod.preInit(FlySwordMod.java:47)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)

	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)

	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)

	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)

	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)

	at net.minecraft.client.main.Main.main(SourceFile:123)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------

-- System Details --

Details:

	Minecraft Version: 1.12.2

	Operating System: Windows 10 (amd64) version 10.0

	Java Version: 1.8.0_171, Oracle Corporation

	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

	Memory: 114928296 bytes (109 MB) / 436207616 bytes (416 MB) up to 4294967296 bytes (4096 MB)

	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump

	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0

	FML: MCP 9.42 Powered by Forge 14.23.5.2838 21 mods loaded, 21 mods active

	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID               | Version          | Source                                     | Signature                                |

	|:----- |:---------------- |:---------------- |:------------------------------------------ |:---------------------------------------- |

	| LCH   | minecraft        | 1.12.2           | minecraft.jar                              | None                                     |

	| LCH   | mcp              | 9.42             | minecraft.jar                              | None                                     |

	| LCH   | FML              | 8.0.99.99        | forge-1.12.2-14.23.5.2838.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	| LCH   | forge            | 14.23.5.2838     | forge-1.12.2-14.23.5.2838.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	| LCH   | jecharacters     | 1.12.0-3.3.0     | JustEnoughCharacters-1.12.0-3.3.0.jar      | None                                     |

	| LCH   | LambdaLib|Core   | 0.1.7            | minecraft.jar                              | None                                     |

	| LCH   | lambdalib2       | 0.1.7            | LambdaLib2-0.1.7.jar                       | None                                     |

	| LCH   | academy          | 1.1.0            | AcademyCraft-1.1.0.jar                     | None                                     |

	| LCH   | baubles          | 1.5.2            | Baubles-1.12-1.5.2.jar                     | None                                     |

	| LCH   | guideapi         | 1.12-2.1.8-63    | Guide-API-1.12-2.1.8-63.jar                | None                                     |

	| LCH   | bloodmagic       | 1.12.2-2.4.1-103 | BloodMagic-1.12.2-2.4.1-103.jar            | None                                     |

	| LCH   | refinedstorage   | 1.6.12           | refinedstorage-1.6.12.jar                  | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |

	| LCH   | compactmachines3 | 3.0.18           | compactmachines3-1.12.2-3.0.18-b278.jar    | None                                     |

	| LCH   | jei              | 4.14.3.237       | jei_1.12.2-4.14.3.237.jar                  | None                                     |

	| LCH   | deepmoblearning  | 1.12.2-2.5.2     | deepmoblearning-1.12.2-2.5.2-universal.jar | None                                     |

	| LCE   | flysword         | 1.0              | flysword-1.0.jar                           | None                                     |

	| LC    | waila            | 1.8.26           | Hwyla-1.8.26-B41_1.12.2.jar                | None                                     |

	| LC    | infernalmobs     | 1.7.6            | InfernalMobs-1.12.1.jar                    | None                                     |

	| LC    | journeymap       | 1.12.2-5.5.3     | journeymap-1.12.2-5.5.3.jar                | None                                     |

	| LC    | magicalcrops     | 1.0.1            | magicalcrops-1.0.2-MC-1.12.jar             | None                                     |

	| LC    | thaumcraft       | 6.1.BETA26       | Thaumcraft-1.12.2-6.1.BETA26.jar           | None                                     |

	Loaded coremods (and transformers): 

JechCore (JustEnoughCharacters-1.12.0-3.3.0.jar)

  me.towdium.jecharacters.core.JechClassTransformer

CorePlugin (LambdaLib2-0.1.7.jar)

  cn.lambdalib2.render.mc.PipelineTransformer

  cn.lambdalib2.registry.impl.RegistryTransformer

	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.86' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'

**Comment by ClaymanTwinkle** [comment]
可能是我传的jar包有问题，我换了一个jar，你可以试试。
如果不行，看看是不是forge的版本太低了，这个模组最低支持到1.12.2-14.23.5.2768
